export * from './panel-1/panel-1.component';
export * from './panel-2/panel-2.component';
export * from './panel-3/panel-3.component';
export * from './panel-4/panel-4.component';
export * from './panel-5/panel-5.component';
export * from './panel-6/panel-6.component';
export * from './panel-7/panel-7.component';
export * from './panel-8/panel-8.component';
export * from './panel-13/panel-13.component';
